version: 2

jobs:
  build_and_test:
    docker:
      - image: circleci/python:2.7
      - image: rabbitmq:3
      - image: mongo:3.4

    steps:
      - checkout
      - run:
          name: Run tests
          command: make all

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
